### ISSUE TITLE
Poster Template

### ISSUE THREAD

**Issue by DevikalyanDas** [StolikTomer/SAGA#3]
Hello, Thanks for your work. I liked your poster. Is it possible for you to provide the template of your poster such that I can use modify it for my work.

**Comment by itailang** [comment]
Dear @DevikalyanDas,

Glad that you liked our poster! You may find the source file [here](https://drive.google.com/file/d/10wdewcYukoAtCfMn2i8bSTXbKxj0l7v1/view?usp=sharing). You are welcome to modify it for your purposes. You can also find a guide about poster preparation [here](https://github.com/itailang/poster_guide).

**Comment by StolikTomer** [comment]
Glad to be of any help :) Good luck!
